### ISSUE TITLE
be rendder

### ISSUE THREAD

**Issue by superon** [Sorenon/images#4]
the 2 images i've tried both output so the top part of one side and the bottom part of the other side doesn't render, leaving the original bed texture there instead

**Comment by Sorenon** [comment]
That's intended, but I may add a different bed which renders like that in a future update

**Comment by superon** [comment]
i can't believe this is intended, hopefully you just misinterpreted what i wrote
https://imgur.com/ZGLrK0n
https://imgur.com/e8kjVBK

**Comment by Sorenon** [comment]
Oh, I see. Yes I completely misunderstood you

**Comment by Sorenon** [comment]
Could you send the URL of the image and a list of other mods

**Comment by superon** [comment]
image link: https://i.imgur.com/eWMxgGL.jpg
image of modslist: https://imgur.com/cibTgPI

**Comment by superon** [comment]
i do get the same result if i disable everything accept fabric api and kotlin and images though

**Comment by Sorenon** [comment]
Thanks for the report, I've just fixed the issue and should have a new build out soonish
